version: '3.8'

services:
  backend:
    build: ./Backend
    ports:
      - "8000:8000"
    volumes:
      - ./Backend:/app
    networks:
      - app-network

  frontend:
    build: ./Frontend/ease-my-trip
    ports:
      - "3000:3000"
    volumes:
      - ./Frontend/ease-my-trip:/app
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
